### ISSUE TITLE
usage of * in package.json

### ISSUE THREAD

**Issue by grawk** [applitools/Eyes.Selenium.JavaScript#1]
Including "latest" selenium-webdriver may be causing issues. I'm trying to use eyes.selenium in my project and when I attempt to require the module, I get this error:

```
undefined:1178
    vlog(2, () => this + ' scheduling notifications', this);
```

I tracked it into selenium-webdriver@2.48.

If you've not verified this particular version, you might want to do so. And also you might want to change the semver for eyes.selenium such that you are locked to a minor version.

**Comment by grawk** [comment]
I found that this seems to have been introduced in selenium-webdriver@2.48 exactly. Would recommend locking to 2.47 for now.

**Comment by Didericis** [comment]
I'm running into the same error in 2.48.0. 2.47 is working without issues.

**Comment by danielputerman** [comment]
Fixed in commits 336e6d6d39a9e8bf827bccc5fc2c7e96acd11f4a and 336e6d6d39a9e8bf827bccc5fc2c7e96acd11f4a. Updated version (0.0.40) is now available in NPM.

**Comment by danielputerman** [comment]
Thanks for the feedback :)

**Comment by knorrium** [comment]
@danielputerman does the eyes.protractor package have to be updated too? thanks!

**Comment by danielputerman** [comment]
I don't think so, but I'll make sure. Thanks for pointing it out.
