### ISSUE TITLE
use it with nightwatch?

### ISSUE THREAD

**Issue by dfguo** [applitools/Eyes.Selenium.JavaScript#3]
how do I use this with nightwatch.js?

**Comment by zavelevsky** [comment]
This SDK is a wrapper for selenium webdriver (https://github.com/SeleniumHQ/selenium/tree/master/javascript/node/selenium-webdriver) - specifically made to work with its task scheduler. nightwatch seems to be an independent implementation - directly using WIRE protocol to communicate with the server.
Until the time a dedicated SDK is released for nightwatch + Applitools eyes - the options are:
1. Use Applitools Eyes images SDK
2. You can potentially create an instance of Eyes (this SDK) and pass the session ID to night watch. This will allow both webdriver and nightwatch to share the same session. Then run your tests like you are used to - and when you want a screenshot taken and uploaded to Applitools you call the instance of Eyes.Selenium.JavaScript you created.

**Comment by dfguo** [comment]
does it work with http://webdriver.io/ or wrapper like webdrivercss?

**Comment by zavelevsky** [comment]
https://github.com/webdriverio/webdrivercss#applitools-eyes-support

**Comment by dfguo** [comment]
awesome
