### ISSUE TITLE
Proper semver support?

### ISSUE THREAD

**Issue by ttdmayshark** [applitools/Eyes.Selenium.JavaScript#46]
![semver](https://user-images.githubusercontent.com/387069/32061111-c3012c50-ba3e-11e7-9e87-dbeaecd7f65a.jpg)

Could you cut a 1.0.0 hard release and then follow normal NPM practices around major/minor/bump releases? As it is, we have to manually bump our consuming package.json to pick up any new release; it would be easier for your end users if we could just specify that we want `^1.0.0` and let semver work properly.

**Comment by danielputerman** [comment]
:) 
1.x version should be released in the next few weeks.
