### ISSUE TITLE
In mobile full-screen tests, the browser address bar continues to repeat.

### ISSUE THREAD

**Issue by KenjiCrosland** [applitools/Eyes.Selenium.JavaScript#47]
When running tests in Sauce Labs that utilize eyes.setStitchMode(Eyes.StichMode.CSS) and eyes.setForceFullPageScreenShot(true), the address bar repeats several times instead of stitching together a single image of the entire page with the nav bar appearing only once at the very top. My understanding is that this doesn't happen when using the Java version of Applitools. However, this does happen when using eyes.selenium in Node while using selenium webdriver.

Example screenshot:
![image](https://user-images.githubusercontent.com/760992/32680839-73d97206-c621-11e7-8379-8d8f0de6bbed.png)

**Comment by wyvern8** [comment]
You should be able to use setImageCut with the FixedCutProvider to exclude the top part of the image.

**Comment by KenjiCrosland** [comment]
@wyvern8 Thank you. That helps. But now in the place of the address bar there is a blank white area  which obscure parts of the layout?
![image](https://user-images.githubusercontent.com/760992/32740763-cd49f48a-c858-11e7-9a41-93642778f889.png)

**Comment by KenjiCrosland** [comment]
Ok I figured it out. Even though I was using FixedCutProvider(130, 0, 0, 0) to cut off the navbar, you need to add it to the footer parameter to offset the white space.

So eyes.setImageCut(new FixedCutProvider(130, 130, 0, 0)); works for safari iphone6
