### ISSUE TITLE
remove controlFlow

### ISSUE THREAD

**Issue by itajaja** [applitools/Eyes.Selenium.JavaScript#66]
`controlFlow` is not a thing anymore in selenium. `driver.controlFlow` should first be checked if present.

I can PR if you guys agree with the approach

**Comment by astappiev** [comment]
Hi @itajaja,

We already working on it, check this repository
https://github.com/applitools/eyes.sdk.javascript1/tree/v4.0.0

We will release a new version very soon.

**Comment by itajaja** [comment]
great! thank you
