### ISSUE TITLE
element.getSize is not a function

### ISSUE THREAD

**Issue by itajaja** [applitools/Eyes.Selenium.JavaScript#67]
`getSize` is not a function in [vanilla selenium](https://seleniumhq.github.io/selenium/docs/api/javascript/index.html) ([changelog](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/CHANGES.md#changes-for-w3c-webdriver-spec-compliance)), so it's impossible to call checkElement or checkRegion with the latest selenium. I see that `getSize` is used multiple times throughout the codebase, is this going to be fixed soon? It is currently impossible to use anything other than `checkWindow`.

**Comment by astappiev** [comment]
Answered here https://github.com/applitools/eyes.sdk.javascript1/issues/52
